### ISSUE TITLE
テスト用(削除しないでね😉)

### ISSUE THREAD

**Issue by hamanyann** [cannon0074/pj-teamReazemi#5]

**Comment by hamanyann** [comment]
owari

**Comment by cannon0074** [comment]
てすと

**Comment by cannon0074** [comment]
![manuaru1](https://github.com/user-attachments/assets/961197e9-1ce6-4ec3-aace-9a68456dabdf)
![manual2](https://github.com/user-attachments/assets/74999786-03df-41ab-9401-aa90cc73d6b1)
